version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - run: cd server && npm install
      - run: cd server && npm test
workflows:
  build-and-test:
    jobs:
      -build-and-test
