version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    machine: true
    steps:
      - checkout          
      - run:
          command: |
            echo "$PASSWORD" | docker login -u "$NAME" --password-stdin
            sudo docker build ./bd -t pduda98/cicd-client
            sudo docker push pduda98/cicd-client
      - run:
          command: |
            echo "$Password" | docker login -u "$NAME" --password-stdin
            sudo docker build ./bd -t pduda/cicd-server
            sudo docker push pduda/cicd-server
  build-and-test-server:
    executor:
      name:  node/default
    steps:
      - checkout
      - run: cd server && npm install
      - run: cd server && npm test
  build-and-test-client:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test-server
      - build-and-test-client
      - deploy
