version: 2.1
orbs:
	node: circleci/node@2.1.0
jobs:
	build-and-test:
		executor: node/default
		steps:
			- checkout
			- node/install-packages
			- run
				command: cd server && npm test
workflows:
	build-and-test:
		jobs:
			-build-and-test
