version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
        environment:
            IMAGE_NAME: pduda98/ask2020-node-react-cicd
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker
            - run:
                command: cd server && docker build -t $IMAGE_NAME:server .
            - run:
                command: |
                    echo "$PASSWORD" | docker login -u "$NAME" --password-stdin
                    docker push server
            - run:
                command: cd client && docker build -t $IMAGENAME:client .
            - run:
                command: |
                    echo "$PASSWORD" | docker login -u "$NAME" --password-stdin
                    docker push client
  build-and-test-server:
    executor:
      name:  node/default
    steps:
      - checkout
      - run: cd server && npm install
      - run: cd server && npm test
  build-and-test-client:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test-server
      - build-and-test-client
      - deploy
